# Generated by Django 5.0.7 on 2024-12-20 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('step_count', models.IntegerField()),
                ('calculated_distance', models.FloatField()),
                ('sleep_duration', models.FloatField()),
                ('stress_level', models.IntegerField()),
                ('hydration_level', models.FloatField()),
                ('activity_level', models.IntegerField()),
                ('bmr', models.FloatField()),
                ('tdee', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
