# Generated by Django 5.0.7 on 2024-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdata',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
