# Generated by Django 5.0.7 on 2024-12-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_fitnessdata_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdata',
            name='height',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
