# Generated by Django 5.0.7 on 2024-12-20 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_fitnessdata_height'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdata',
            name='activity_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fitnessdata',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fitnessdata',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fitnessdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
